---
# Playbook to prepare the local host for building windows boot ISO images
- hosts: localhost
  connection: local
  vars:
    generated_dir: "{{playbook_dir}}/generated"
    files_dir: "{{playbook_dir}}/downloaded"
    # ISO names
    virtio_win_iso: "virtio-win.iso"
    cloudbase_init_installer: "CloudbaseInitSetup_Stable_x64.msi"
    win_2k19_iso: "17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
    win7_iso: en_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677791.iso
    # Software Names
    procmon_installer: ProcessMonitor.zip
    firefox_installer: firefox-setup.exe
    vscode_installer: vscode-setup.exe
  tasks:
    - name: Ensure files dir exists
      file:
        path: "{{files_dir}}"
        state: directory

    - name: Ensure files dir exists
      file:
        path: "{{generated_dir}}"
        state: directory

    - name: Download virtio drivers
      block:
        - name: Downloading latest stable virtio drivers
          get_url:
            url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
            dest: "{{files_dir}}/{{virtio_win_iso}}"

    - name: Download cloudbase-init drivers
      block:
        - name: installer dir
          file:
            path: "{{files_dir}}/cloudbase-init/"
            state: directory
        - get_url:
            url: https://cloudbase.it/downloads/CloudbaseInitSetup_Stable_x64.msi
            dest: "{{files_dir}}/cloudbase-init/{{cloudbase_init_installer}}"

    # Download some tools to make Windows more palatable
    - name: Download Process Monitor
      block:
        - file:
            path: "{{files_dir}}"
            state: directory
        - get_url:
            url: https://download.sysinternals.com/files/ProcessMonitor.zip
            dest: "{{files_dir}}/{{procmon_installer}}"

    - name: Download Firefox Offline
      block:
        - file:
            path: "{{files_dir}}"
            state: directory
        - get_url:
            url: https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US
            dest: "{{files_dir}}/{{firefox_installer}}"

    - name: Download VS Code Offline
      block:
        - file:
            path: "{{files_dir}}"
            state: directory
        - get_url:
            url: https://code.visualstudio.com/sha/download?build=stable&os=win32-x64
            dest: "{{files_dir}}/{{vscode_installer}}"


    - name: Check for Windows ISO files
      block:
        - name: Windows Server 2019 ISO must exist
          stat:
            path: "{{files_dir}}/{{win_2k19_iso}}"
          register: win_wk19_st
          failed_when: not win_wk19_st.stat.exists

        - name: win-7-unattended-virtio-image-updated.iso
        - get_url:
            url: https://the-eye.eu/public/MSDN/Windows%207/en_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677791.iso
            dest: "{{files_dir}}/{{win7.iso}}"
          register: win_7_st
          failed_when: not win_7_st.stat.exists

    - name: Install launch-cloud-image dependencies
      become: true
      package:
        name:
          - libvirt-daemon
          - libvirt-daemon-system
          - libvirt-daemon-driver-qemu
          - libvirt-clients
          - qemu-utils
          - ovmf
          - fuseiso
          - udftools
          - jq
          - numad
        state: latest

    - name: Install Windows ISO manipulation dependencies
      become: true
      package:
        name:
          - xorriso
          - rsync
          - fuse
          - wimtools
          - xmlstarlet
        state: latest

    - name: check udisksctl is usable
      command: udisksctl help
      changed_when: False
