---
# Playbook to prepare the local host for building windows boot ISO images
- hosts: localhost
  connection: local
  vars:
    generated_dir: "{{playbook_dir}}/generated"
    files_dir: "{{playbook_dir}}/downloaded"
    # ISO names
    virtio_win_iso: "virtio-win.iso"
    cloudbase_init_installer: "CloudbaseInitSetup_Stable_x64.msi"
    win_2k19_iso: "17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
    win10_iso: "Win10_20H2_v2_English_x64.iso"
    win7_iso: en_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677791.iso
    ubuntu2404_iso: ubuntu-24.04-desktop-amd64.iso
    # Software Names
    procmon_installer: ProcessMonitor.zip
    firefox_installer: firefox-setup.exe
    vscode_installer: vscode-setup.exe
  tasks:
    - name: Ensure files dir exists
      file:
        path: "{{files_dir}}"
        state: directory

    - name: Ensure files dir exists
      file:
        path: "{{generated_dir}}"
        state: directory

    - name: Download virtio drivers
      block:
        - name: Downloading latest stable virtio drivers
          get_url:
            url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
            dest: "{{files_dir}}/{{virtio_win_iso}}"

    - name: Download cloudbase-init drivers
      block:
        - name: installer dir
          file:
            path: "{{files_dir}}/cloudbase-init/"
            state: directory
        - get_url:
            url: https://cloudbase.it/downloads/CloudbaseInitSetup_Stable_x64.msi
            dest: "{{files_dir}}/cloudbase-init/{{cloudbase_init_installer}}"

    # Download some tools to make Windows more palatable
    - name: Download Process Monitor
      block:
        - file:
            path: "{{files_dir}}"
            state: directory
        - get_url:
            url: https://download.sysinternals.com/files/ProcessMonitor.zip
            dest: "{{files_dir}}/{{procmon_installer}}"

    - name: Download Firefox Offline
      block:
        - file:
            path: "{{files_dir}}"
            state: directory
        - get_url:
            url: https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US
            dest: "{{files_dir}}/{{firefox_installer}}"

    - name: Download VS Code Offline
      block:
        - file:
            path: "{{files_dir}}"
            state: directory
        - get_url:
            url: https://code.visualstudio.com/sha/download?build=stable&os=win32-x64
            dest: "{{files_dir}}/{{vscode_installer}}"


    - name: Check for Windows Server 2K19 ISO files
      block:
        - name: Windows Server 2019 ISO must exist
          stat:
            path: "{{files_dir}}/{{win_2k19_iso}}"
          register: win_wk19_st
          when: not win_wk19_st.stat.exists

        # - name: Download Win 2K19 ISO
        #   get_url:
        #     url: https://the-eye.eu/public/MSDN/Windows%207/en_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677791.iso
        #     dest: "{{files_dir}}/{{win7_iso}}"
        #   when: not win_wk19_st.stat.exists

    - name: Check for Windows 10 ISO files
      block:
        - name: Windows 10 ISO must exist
          stat:
            path: "{{files_dir}}/{{win10_iso}}"
          register: win_10_st

        - name: Download the Win 7 ISO
          get_url:
            url: https://software-download.microsoft.com/sg/Win10_20H2_v2_English_x64.iso?t=e9868523-e6f5-4804-8e43-1db4340f3615&e=1621343235&h=0ae68227da3db427fb472f65bd4c6894
            dest: "{{files_dir}}/{{win7_iso}}"
          when: not win_10_st.stat.exists

    - name: Check for Windows 7 ISO files
      block:
        - name: Windows 7 ISO must exist
          stat:
            path: "{{files_dir}}/{{win7_iso}}"
          register: win_7_st

        - name: Download the Win 7 ISO
          get_url:
            url: https://the-eye.eu/public/MSDN/Windows%207/en_windows_7_professional_with_sp1_vl_build_x64_dvd_u_677791.iso
            dest: "{{files_dir}}/{{win7_iso}}"
          when: not win_7_st.stat.exists

    - name: Check for Ubuntu 24.04 ISO files
      block:
        - name: Ubuntu 24.04 ISO must exist
          stat:
            path: "{{files_dir}}/{{ubuntu2404_iso}}"
          register: ubuntu2404_st

        - name: Download the Ubuntu 24.04 ISO
          get_url:
            url: https://mirror.aarnet.edu.au/pub/ubuntu/releases/24.04/ubuntu-24.04-desktop-amd64.iso
            dest: "{{files_dir}}/{{ubuntu2404_iso}}"
          when: not ubuntu2404_st.stat.exists

    - name: Install launch-cloud-image dependencies
      become: true
      package:
        name:
          - libvirt-daemon
          - libvirt-daemon-system
          - libvirt-daemon-driver-qemu
          - libvirt-clients
          - qemu-utils
          - ovmf
          - fuseiso
          - udftools
          - jq
          - numad
          - swtpm-tools
        state: latest

    - name: Install Windows ISO manipulation dependencies
      become: true
      package:
        name:
          - xorriso
          - rsync
          - fuse
          - wimtools
          - xmlstarlet
        state: latest

    - name: check udisksctl is usable
      command: udisksctl help
      changed_when: False
